# Generated by Django 2.0.6 on 2019-06-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autism', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
