# Generated by Django 2.2.4 on 2019-10-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autism', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
