# Generated by Django 2.0.6 on 2019-11-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autism', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
